### ISSUE TITLE
nfmovies 失效

### ISSUE THREAD

**Issue by xixaxoqiqaqo** [limbopro/Adblock4limbo#1]
![A6464060-CDB9-4566-8599-4AA7666F8DAC](https://user-images.githubusercontent.com/78405720/109283810-28184100-785a-11eb-9ecf-9fd3f1be49f8.jpeg)

**Comment by limbopro** [comment]
参考 https://github.com/limbopro/Adblock4limbo 中使用方法食用。

**Comment by xixaxoqiqaqo** [comment]
> 参考 https://github.com/limbopro/Adblock4limbo 中使用方法食用。

- 是复写顺序的问题，但是现在无法观看视频提示 video load falied

**Comment by limbopro** [comment]
参考 https://github.com/limbopro/Adblock4limbo 中使用方法食用。
