### ISSUE TITLE
播放抖音时，日志会出现mimt fail的现象

### ISSUE THREAD

**Issue by liukaiwen0422** [limbopro/Adblock4limbo#10]
![image](https://user-images.githubusercontent.com/53621063/160527510-228d1290-c880-4276-9a01-0e323446af41.jpeg)
但是刷抖音也能正常刷，就是会出现这个

**Comment by limbopro** [comment]
如果不看TikTok ，可在在主机名处添加 -*.amemv.com 
![92FECC2B-D4B8-49B6-ACC2-86CBF4F57810](https://user-images.githubusercontent.com/53378607/160528240-832387d3-534a-4824-b4ab-ade6b9a3b693.jpeg)

**Comment by liukaiwen0422** [comment]
> 如果不看TikTok ，可在在主机名处添加 -*.amemv.com 
> 
> ![92FECC2B-D4B8-49B6-ACC2-86CBF4F57810](https://user-images.githubusercontent.com/53378607/160528240-832387d3-534a-4824-b4ab-ade6b9a3b693.jpeg)
> 
> 

好的，谢谢
