### ISSUE TITLE
没太看明白，这个东西可以放到AdGuard home里面用吗？

### ISSUE THREAD

**Issue by Seeger0216** [limbopro/Adblock4limbo#11]
AdGuard home是个DNS服务器，不知道能不能导入这个规则用诶？现在大多广告都去掉了，但Instagram app里面的赞助内容没去掉，赞助内容太频繁了，看story，一个我关注的人接一个赞助内容，很影响体验。

**Comment by Seeger0216** [comment]
我看AdGuard home有个自定义规则是这么写的，
/REGEX/ – 阻止访问与指定的正则表达式匹配的域名
我去试试看吧

**Comment by Karmylr** [comment]
@Seeger0216 不行
