### ISSUE TITLE
anime1 ，去广告

### ISSUE THREAD

**Issue by laincat** [limbopro/Adblock4limbo#22]
https://anime1.me/

来一发？

**Comment by coolicer** [comment]
樱花动漫类也要

**Comment by limbopro** [comment]
https://anime1.me/ 去广告已完成；QuantumultX / 油猴脚本均已支持，Surge 待更新；

**Comment by laincat** [comment]
加载 模块 后，无法打开选择的视频页…

**Comment by limbopro** [comment]
> 加载 模块 后，无法打开选择的视频页…

已修复，更新模块后食用；https://github.com/limbopro/Adblock4limbo/commit/214f3b743fcc463a86dd666bdba35ec8d55212e1
