### ISSUE TITLE
请求去除樱花动漫广告

### ISSUE THREAD

**Issue by Zxazz** [limbopro/Adblock4limbo#23]
https://m.yhpdm.com/showp/22350.html

**Comment by ahsisnwk** [comment]
#>樱花动漫
hostname=m.yhpdm.com
^https?:\/\/m\.yhpdm\.com.* url script-response-body yinghua.js

**Comment by ahsisnwk** [comment]
var body=$response.body;

body=body.replace(/[\s\S]*(?=<script>[\s\S]*?var _hmt)/g,'');

$done(body);

**Comment by limbopro** [comment]
已支持。

yhdmp: ".yrtjbmnk_b, .hvitsutz_b {display :none !important; pointer-events: none !important;}", // 樱花动漫
