### ISSUE TITLE
请求去哔嘀影视广告

### ISSUE THREAD

**Issue by www1023www** [limbopro/Adblock4limbo#24]
www.bdys01.com
![95B74EF1-3443-4EB1-939F-A342B7CF8216](https://user-images.githubusercontent.com/125802786/221075924-d9be58fc-c6d1-4376-b1e4-190392ec8925.png)

**Comment by limbopro** [comment]
@www1023www

**Comment by limbopro** [comment]
![53A76DF2-A905-4AF3-A3EF-6807F8BC88DA](https://user-images.githubusercontent.com/53378607/221079221-c9a79a2e-5540-4b7c-9108-4f11622ece2f.png)

不要瞎几把提交issue。
