### ISSUE TITLE
安装 surge 模块后无法访问 pornhub

### ISSUE THREAD

**Issue by ch634421335** [limbopro/Adblock4limbo#28]
安装的模块地址： https://limbopro.com/Adblock4limbo.sgmodule
访问地址： 'https://www.pornhub.com/' 
网页显示：  ![网页显示](https://i.imgur.com/Jk38H7I.png) 
surge 日志： ![日志](https://i.imgur.com/a5GaaqX.png) 
把这个模块禁用掉就能正常访问了。

**Comment by limbopro** [comment]
直接访问 cn.p***.com
