### ISSUE TITLE
nfmovies出现广告未完全去除情况

### ISSUE THREAD

**Issue by xlangzhong** [limbopro/Adblock4limbo#3]
设备：iPad 2018
使用该项目进行去广告时，右下角有白条广告未完全去除
![image](https://user-images.githubusercontent.com/71161243/122933788-88029c80-d3a1-11eb-88d2-df8c9933230b.png)

**Comment by limbopro** [comment]
@xlangzhong 晚上看看

**Comment by xlangzhong** [comment]
> @xlangzhong 晚上看看

好的👌

**Comment by limbopro** [comment]
已修复；
