### ISSUE TITLE
请求去除免费外文电子书下载网站的页面广告

### ISSUE THREAD

**Issue by ShrikeZXL** [limbopro/Adblock4limbo#30]
https://www.planetebook.com/
很奇怪的是电脑端打开界面一直很纯净，但iPhone和ipad打开就在顶栏有广告

**Comment by limbopro** [comment]
@ShrikeZXL 因为这网站我们压根没支持

**Comment by limbopro** [comment]
确保按文章 https://limbopro.com/archives/12904.html 说明引用模块/重写以及分流规则(并选择reject)，现在更新一下模块/重写以及分流，清除浏览器缓存重新访问即可。
