### ISSUE TITLE
常用广告关键词

### ISSUE THREAD

**Issue by Yiran-biby** [limbopro/Adblock4limbo#31]
建议添加常用广告关键词规则进入分流list。

https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list

**Comment by limbopro** [comment]
已加。https://raw.githubusercontent.com/limbopro/Adblock4limbo/main/Adblock4limbo.list https://raw.githubusercontent.com/limbopro/Adblock4limbo/main/Adblock4limbo_surge.list
