### ISSUE TITLE
BiliBili无法搜索

### ISSUE THREAD

**Issue by a776058959** [limbopro/Adblock4limbo#33]
![image](https://github.com/limbopro/Adblock4limbo/assets/58454818/cfe11ab3-8a66-49f0-8017-5c07b20a0f45)
应该不是和其他脚本冲突，把其他脚本都关掉也是无法搜索，搜索框打了字之后回车没任何反应。

目前我是加了`// @exclude      https://*.bilibili.*` 来排除B站。

**Comment by limbopro** [comment]
已修复。
