### ISSUE TITLE
嚴重卡頓而且還套用到全域太狠了

### ISSUE THREAD

**Issue by hoshugon** [limbopro/Adblock4limbo#34]
一直感覺網頁很卡，想說是不是電腦哪邊有問題，找半天是這個腳本在搞鬼，

沒事套用全域做什麼，本身卡就算了，還讓每個網頁都卡，太垃圾了。

**Comment by limbopro** [comment]
@hoshugon 由于最近版本（最近3-4天左右）复制脚本时未删除 match *.*， 导致本脚本对其他域名网页造成影响。目前已修复。
