### ISSUE TITLE
泥视频广告

### ISSUE THREAD

**Issue by wellerbarry** [limbopro/Adblock4limbo#35]
每次打开泥视频总会弹出2次广告，打开视频封面再来2次，麻烦大佬看看
![IMG_0540](https://github.com/limbopro/Adblock4limbo/assets/147250590/9712a71f-95b5-4cfb-b220-caba2acf15d6)
![IMG_0541](https://github.com/limbopro/Adblock4limbo/assets/147250590/55c15b16-9f35-4106-bfa4-7230636fb4ae)
![IMG_0542](https://github.com/limbopro/Adblock4limbo/assets/147250590/a30e1c8a-e90e-4ac1-a379-4830ec6c2ca7)

**Comment by limbopro** [comment]
测试没看到相关广告。

**Comment by wellerbarry** [comment]
我用的是Stay免费的脚本功能，如果单独去这个视频网需要哪些代码，大佬可否告知下，谢谢

**Comment by limbopro** [comment]
确保已安装最新版用户脚本，用户脚本地址：https://github.com/limbopro/Adblock4limbo/raw/main/Adguard/Adblock4limbo.user.js / https://sleazyfork.org/zh-CN/scripts/443290-adblock4limbo； 并配合去广告分流食用：https://github.com/limbopro/Adblock4limbo/tree/main/rule -> Adblock4limbo_surge.list/Adblock4limbo.list

**Comment by wellerbarry** [comment]
安装Adblock4limbo.X ver.0.3.10.01脚本后，图一图二的广告消失了👍，图三和跳转到App store的链接开始弹出二次，后来没有了，待观察一下再反馈.

后面这段应该怎么操作？
并配合去广告分流食用：https://github.com/limbopro/Adblock4limbo/tree/main/rule -> Adblock4limbo_surge.list/Adblock4limbo.list

**Comment by limbopro** [comment]
需配合代理软件(如QuantumultX/Shadowrocket)食用，如不会操作或未购买相应软件可忽略此步骤。

**Comment by wellerbarry** [comment]
能添加这个脚本相关代码到毒奶计划脚本的测试版吗？
https://sleazyfork.org/zh-CN/scripts/476250-泥视频广告跳过与直接播放重定向

**Comment by limbopro** [comment]
@wellerbarry 不需要添加，现有脚本已实现广告跳过。
