### ISSUE TITLE
谷歌搜索页无法加载下一页

### ISSUE THREAD

**Issue by CY-Christin** [limbopro/Adblock4limbo#36]
**简要描述该问题**
使用今日新更新的 surge module 后在谷歌任意搜索内容，点击下一页无法加载，一直在转圈，关闭模块后就正常了。
**问题重现步骤**
重现该行为的步骤：
1. 在哪个网页 '谷歌搜索结果页'
3. 做了什么 '点击下一页'
4. 出现了什么问题 '一直在转圈，无法加载下一页内容'
5. Gif广告/视频广告/图片广告/弹窗...

**预期想要得到的结果**
可以正常加载

**页面截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**操作系统及浏览器（请填写以下信息）:** 如没有则填无需填写
 - 系统: [mac]
 - 浏览器 [chrome & arc ]
 - 代理工具 [Surge]
 - 引用的重写/或模块链接 [ https://limbopro.com/Adblock4limbo.sgmodule ]
 - 油猴脚本安装地址 []

**额外的背景信息**
在此处添加有关该问题的任何其他上下文。
<img width="700" alt="image" src="https://github.com/limbopro/Adblock4limbo/assets/46257384/14a49101-8ac8-4712-bea0-9428990bf3ad">

查看控制台有报错  
<img width="1168" alt="image" src="https://github.com/limbopro/Adblock4limbo/assets/46257384/9990a621-95a8-4fce-be28-f5cdc2efc959">

**Comment by limbopro** [comment]
已修复：https://github.com/limbopro/Adblock4limbo/commit/58a157767b6dac1cefc106c83636c7d25dbf3a8e#diff-2a35a10c20bb6d88671a26edf3a6c010c00fd5d6a59a83aa83ede5d31f41b692
