### ISSUE TITLE
B站视频播放页无法搜索，其他页面正常

### ISSUE THREAD

**Issue by a776058959** [limbopro/Adblock4limbo#37]
**简要描述该问题**
B站视频播放页无法搜索，其他页面正常
**问题重现步骤**
重现该行为的步骤：
1. B站视频播放页
3. 点击搜索框搜索
4. 没有任何反应

**页面截图**
![图片](https://github.com/limbopro/Adblock4limbo/assets/58454818/835ad65b-ec3e-4f9e-9c27-594946a00bdd)

**操作系统及浏览器（请填写以下信息）:** 如没有则填无需填写
 - 系统: ：Win11
 - 浏览器 ：Firefox 119.0
 - 代理工具 ：无
 - 引用的重写/或模块链接 [e.g. https://limbopro.com/Adblock4limbo.conf / https://limbopro.com/Adblock4limbo.sgmodule ]
 - 油猴脚本安装地址 [e.d. https://github.com/limbopro/Adblock4limbo/raw/main/Adguard/Adblock4limbo.user.js / https://greasyfork.org/scripts/443290-adblock4limbo/code/Adblock4limbo.user.js]

**额外的背景信息**
无

**Comment by limbopro** [comment]
已修复：https://github.com/limbopro/Adblock4limbo/commit/26c2f16a59d53c4cab744b3da91d1f00e5969004#diff-809e9b9006010aa6aaba2da7e4d96efd93edd42d55c16937b61a933fa2e50727 ，推荐优先安装 https://github.com/limbopro/Adblock4limbo/raw/main/Adguard/Adblock4limbo.user.js
