### ISSUE TITLE
脚本误伤了网站的菜单

### ISSUE THREAD

**Issue by weiby3** [limbopro/Adblock4limbo#38]
**简要描述该问题**
https://github.com/ba-archive/blue-archive/issues/204
参考上面的issue，脚本将网站的菜单去掉了。

**问题重现步骤**
安装脚本，打开https://blue-archive.io/

**预期想要得到的结果**
防止误伤

**Comment by limbopro** [comment]
已暂时将 https://blue-archive.io/ 排除，更新至最新版本 ： https://github.com/limbopro/Adblock4limbo/raw/main/Adguard/Adblock4limbo.user.js ；（因为该网站与本脚本使用了同一个CSS样式ID #navigation ，所以在使用油猴脚本时导致该网站的导航被隐藏误伤；我们暂时不会修改ID命名方式;

**Comment by Mark9804** [comment]
`#navigation, #nav` 还是还是挺经常使用的，能否使用粒度更细的选择器呢

**Comment by limbopro** [comment]
@Mark9804 待周末优化。
