### ISSUE TITLE
Google 的推荐广告

### ISSUE THREAD

**Issue by kewachan** [limbopro/Adblock4limbo#40]
该网站地址：
Www.google.com

问题重现步骤
在私密模式的safari中，第一次搜寻 2 个以上的关键字

重现该行为的步骤：
搜索2个以上的关键字

在哪个网页出现了广告 '一个小弹窗'
做了什么 '搜寻2个以上的关键字, 例如, 搜寻“上海 twitter”'
出现了什么广告 '出现了一个Fast access to Google
Get the new Google widget的弹窗'![image](https://github.com/limbopro/Adblock4limbo/assets/12181657/8b4f8f5a-53e7-45a6-b63c-d81b4d217595)
Gif广告/视频广告/图片广告/弹窗...
预期想要得到的结果
对您期望发生的情况的清晰简洁的描述。

页面截图
如果适用，请添加屏幕截图以帮助解释您的问题。

操作系统及浏览器（请填写以下信息）:

OS: [17.2]
Browser [safari]
Version [22]
Network tool [QuantmultX]
额外的背景信息
在此处添加有关该问题的任何其他上下文。

**Comment by limbopro** [comment]
@kewachan 按文章说明配置重写和分流即可移除该提示/弹窗：https://limbopro.com/archives/12904.html ；此前已有用户反馈在 Safari 无痕模式下，谷歌搜索 提示登录/下载App，涉及选择器：div.XDZKBc, .jnyxRd.TpRPV 。
