### ISSUE TITLE
希望能添加tvbanywherena.com网页

### ISSUE THREAD

**Issue by wellerbarry** [limbopro/Adblock4limbo#41]
希望能添加该网站地址：https://www.tvbanywherena.com/cantonese/videos/620-HongKongNews/1781370688091670870

重现该行为的步骤：视频播放前有15秒广告，网页有其它广告

出现了什么广告：视频广告/图片广告/弹窗
预期想要得到的结果：去除各类广告，

页面截图
![IMG_0699](https://github.com/limbopro/Adblock4limbo/assets/147250590/6a7786e4-b865-4c8d-823b-a6d2079f592e)
![IMG_0698](https://github.com/limbopro/Adblock4limbo/assets/147250590/dfc5d273-22e4-4694-9403-81e71ebacba0)
![IMG_0697](https://github.com/limbopro/Adblock4limbo/assets/147250590/9eec75fb-24ad-413c-8a05-ea812d0ace6e)
![IMG_0696](https://github.com/limbopro/Adblock4limbo/assets/147250590/c91535b4-6f92-49aa-8779-bf0ffc88eadc)

操作系统及浏览器
OS: [iOS 17.1]
Browser [Safari]
Version [17.1]
Network tool [Stay]

**Comment by limbopro** [comment]
@wellerbarry 按文章https://limbopro.com/archives/12904.html#%E6%9B%B4%E5%A4%9A%E5%8E%BB%E5%B9%BF%E5%91%8A%E5%88%86%E6%B5%81%EF%BC%88%E5%8F%AF%E4%BE%9B%E9%80%89%E6%8B%A9%EF%BC%89 中 更多去广告分流（可供选择）部分的说明，添加去广告分流，可以解决大部分广告联盟的广告。

**Comment by wellerbarry** [comment]
感谢回复，请问有脚本类的方式能实现吗？

**Comment by wellerbarry** [comment]
> @wellerbarry 按文章https://limbopro.com/archives/12904.html#%E6%9B%B4%E5%A4%9A%E5%8E%BB%E5%B9%BF%E5%91%8A%E5%88%86%E6%B5%81%EF%BC%88%E5%8F%AF%E4%BE%9B%E9%80%89%E6%8B%A9%EF%BC%89 中 更多去广告分流（可供选择）部分的说明，添加去广告分流，可以解决大部分广告联盟的广告。

请问用Stay脚本能实现吗？谢谢

**Comment by limbopro** [comment]
@wellerbarry 暂无支持计划。
