### ISSUE TITLE
启用了这个脚本会导致b站直播卡顿，油管观看时拖动网页会有黑块

### ISSUE THREAD

**Issue by freeruaman** [limbopro/Adblock4limbo#43]
**简要描述该问题**

**问题重现步骤**
重现该行为的步骤：
1. 在哪个网页 '...'
3. 做了什么 '....'
4. 出现了什么问题 '....'
5. Gif广告/视频广告/图片广告/弹窗...

**预期想要得到的结果**
对您期望发生的情况的清晰简洁的描述。

**页面截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**操作系统及浏览器（请填写以下信息）:** 如没有则填无需填写
 - 系统: [e.g. iOS/PC]
 - 浏览器 [e.g. chrome, safari]
 - 代理工具 [e.g. QuantmultX/Surge]
 - 引用的重写/或模块链接 [e.g. https://limbopro.com/Adblock4limbo.conf / https://limbopro.com/Adblock4limbo.sgmodule ]
 - 油猴脚本安装地址 [e.d. https://github.com/limbopro/Adblock4limbo/raw/main/Adguard/Adblock4limbo.user.js / https://greasyfork.org/scripts/443290-adblock4limbo/code/Adblock4limbo.user.js]

**额外的背景信息**
在此处添加有关该问题的任何其他上下文。

**Comment by limbopro** [comment]
@freeruaman 未发现相应问题。
