### ISSUE TITLE
禁漫天堂网站https://18comic-fun.xyz/无法屏蔽广告，目前好像只能屏蔽18comic.vip/org

### ISSUE THREAD

**Issue by xander886** [limbopro/Adblock4limbo#45]
该网站地址：

问题重现步骤
重现该行为的步骤：

在哪个网页出现了广告 '...'
做了什么 '....'
出现了什么广告 '....'
Gif广告/视频广告/图片广告/弹窗...
预期想要得到的结果
对您期望发生的情况的清晰简洁的描述。

页面截图
如果适用，请添加屏幕截图以帮助解释您的问题。

操作系统及浏览器（请填写以下信息）:

Network tool [e.g. QuantmultX]
额外的背景信息
在此处添加有关该问题的任何其他上下文。

**Comment by limbopro** [comment]
@xander886 对

**Comment by xander886** [comment]
有办法在里面添加屏蔽的网址吗
