### ISSUE TITLE
过滤广告后，页面布局错乱

### ISSUE THREAD

**Issue by jimmylzt188** [limbopro/Adblock4limbo#47]
**简要描述该问题**
https://www.macat.vip/ 启动过滤后，页面中软件卡片会缩小，且布局乱了

**页面截图**
<img width="388" alt="image" src="https://github.com/limbopro/Adblock4limbo/assets/69511217/67f50039-f067-4640-9db5-6ac742f0bc27">

**操作系统及浏览器（请填写以下信息）:** 如没有则填无需填写
 - 系统: [e.g. iOS/PC]
 - 浏览器 [e.g. chrome, safari]
 - 代理工具 [e.g. QuantmultX/Surge]
 - 引用的重写/或模块链接 [e.g. https://limbopro.com/Adblock4limbo.conf / https://limbopro.com/Adblock4limbo.sgmodule ]
 - 油猴脚本安装地址 [e.d. https://github.com/limbopro/Adblock4limbo/raw/main/Adguard/Adblock4limbo.user.js / https://greasyfork.org/scripts/443290-adblock4limbo/code/Adblock4limbo.user.js]

**额外的背景信息**
在此处添加有关该问题的任何其他上下文。

**Comment by limbopro** [comment]
@jimmylzt188 请提供更多细节。
