### ISSUE TITLE
知乎评论出现“资源不存在”错误

### ISSUE THREAD

**Issue by QuantumRoseinAmethystVase** [limbopro/Adblock4limbo#48]
**简要描述该问题**
启用模块后，打开知乎网页的评论会出现错误

**问题重现步骤**
重现该行为的步骤：
1. 知乎 'https://www.zhihu.com/'
3. 做了什么 '随意点开一个评论'
4. 出现了什么问题 '加载无法评论且出现“资源不存在”错误'

**预期想要得到的结果**
出现评论

**页面截图**
<img width="1002" alt="image" src="https://github.com/limbopro/Adblock4limbo/assets/62452364/3e996333-26c1-4025-9e0d-611de34393be">

<img width="1159" alt="image" src="https://github.com/limbopro/Adblock4limbo/assets/62452364/a9d76c19-f4cb-4d55-94c7-383349e08cd3">

**操作系统及浏览器（请填写以下信息）:** 如没有则填无需填写
 - 系统: [macOS]
 - 浏览器 [Arc]
 - 代理工具 [Surge]
 - 引用的重写/或模块链接 [https://limbopro.com/Adblock4limbo.sgmodule ]

**Comment by limbopro** [comment]
@QuantumRoseinAmethystVase 请禁用模块后重新打开评论区看问题是否依旧。

**Comment by QuantumRoseinAmethystVase** [comment]
> @QuantumRoseinAmethystVase 请禁用模块后重新打开评论区看问题是否依旧。

禁用后正常加载评论，问题消失。
