### ISSUE TITLE
启用脚本导致腾讯文档页面排版错乱

### ISSUE THREAD

**Issue by iseeyo** [limbopro/Adblock4limbo#49]
相关页面 https://docs.qq.com/mall/index?folder=&from_page=doc_list_new_smartcanvas
![image](https://github.com/limbopro/Adblock4limbo/assets/7778828/8c37e115-104a-46e6-9157-438263398d5e)

**Comment by limbopro** [comment]
@iseeyo 需要提供更多信息，使用的代理软件，涉及的模块或重写等等。
