### ISSUE TITLE
TingFM 将停止对屏蔽广告用户的服务

### ISSUE THREAD

**Issue by xixaxoqiqaqo** [limbopro/Adblock4limbo#5]
![C5A3E8E3-8640-4F56-AE49-9D1DB895AE22](https://user-images.githubusercontent.com/78405720/126309199-d69b7eed-2ba4-4c10-a712-5f8e7b099fed.jpeg)

**Comment by limbopro** [comment]
本去广告计划未针对该tingfm进行去广告，请自行查看qx网络活动日志。本计划不会为之提供任何相关帮助。

**Comment by xixaxoqiqaqo** [comment]
> 本去广告计划未针对该tingfm进行去广告，请自行查看qx网络活动日志。本计划不会为之提供任何相关帮助。

- 感谢 Adblock4limbo，希望可以支持更多网站
- TingFM 是本来就去除了广告，不需要再进行去广告，打扰了
