### ISSUE TITLE
小宝影院页面出现了广告

### ISSUE THREAD

**Issue by wellerbarry** [limbopro/Adblock4limbo#52]
**简要描述该问题**
小宝影视的域名已经改为https://xiaoxintv.net/
                                          https://vip.xiaoxintv.net/

**问题重现步骤**
重现该行为的步骤：
在哪个网页 ：https://xiaoxintv.net/
                       https://vip.xiaoxintv.net/
出现了什么问题：去广告在新域名不起作用

**预期想要得到的结果**
更新两个新域名到去广告计划里

**操作系统及浏览器（请填写以下信息）:** 如没有则填无需填写
 - 系统： iOS 17.3.1
 - 浏览器：Safari
 - 代理工具：Stay
 - 油猴脚本安装地址：
https://update.sleazyfork.org/scripts/443290/Adblock4limbo.user.js

**Comment by limbopro** [comment]
小宝影院本身没广告的，我记得。如果你使用代理软件如qx，surge 之类可以尝试添加相应去广告分流：https://limbopro.com/archives/12904.html
