### ISSUE TITLE
iphone使用规则某些网站无法使用

### ISSUE THREAD

**Issue by alpha0928** [limbopro/Adblock4limbo#53]
iphone使用chrome浏览器或者safari浏览器利用毒奶去广告计划（for Shadowrocket）的时候，某些网站无法使用，显示按esc/轻点/上滑屏幕以解除模糊，手机屏幕没有esc键，轻点或者上滑会重复出现这个提示，无法观看视频。可以告诉解决方法嘛~
- 系统: [iOS]
- 浏览器 [chrome, safari]
- 代理工具 [Shadowrocket]
- 
![lQDPJx8QeEZIR_PNCfzNBJuwLqNrJ3AsB-IFznTkwhSMAA_1179_2556](https://github.com/limbopro/Adblock4limbo/assets/12199695/a791b05f-e7c3-48e3-98ac-6bcc50bf55ae)

**Comment by limbopro** [comment]
@alpha0928 刷新当前网页，点击3次屏幕

**Comment by alpha0928** [comment]
第三个屏幕是什么意思😅

毒奶博主 ***@***.***> 于2024年2月29日周四 13:45写道：

**Comment by alpha0928** [comment]
@limbopro 第三个屏幕是什么意思

**Comment by alpha0928** [comment]
@limbopro 第三个屏幕是什么意思？麻烦说下详细步骤，谢谢！

**Comment by limbopro** [comment]
@alpha0928 字面意思，点击三次屏幕即可解除模糊。

**Comment by alpha0928** [comment]
@limbopro  试过了 还是无法解决，刷新后点击三次依旧出现这个页面~

**Comment by limbopro** [comment]
@alpha0928 那就不懂了 可能你的浏览器有自己的想法💡 自己试着排查下吧
