### ISSUE TITLE
Twitter广告无法去除

### ISSUE THREAD

**Issue by Gateway11** [limbopro/Adblock4limbo#54]
该网站地址：https://twitter.com/home

问题重现步骤
重现该行为的步骤：主页第三条内容大概率会显示广告

预期想要得到的结果：更新下面两个链接的去广告规则
https://[limbopro.com/](http://limbopro.com/)Adblock4limbo.module
https://[limbopro.com/Adblock4limbo.list](http://limbopro.com/Adblock4limbo.list)

页面截图

![image](https://github.com/limbopro/Adblock4limbo/assets/15076065/5f5dbefc-4f54-4db8-99e0-48c22dbc25ab)

操作系统及浏览器（请填写以下信息）:

OS: IOS 16.7.1
Browser：Safari
Network tool [Shadowrocket]

**Comment by limbopro** [comment]
@Gateway11 Twitter 不在去广告计划范围。
