### ISSUE TITLE
什么值得买app的开屏广告能屏蔽么？谢谢

### ISSUE THREAD

**Issue by kerryeva** [limbopro/Adblock4limbo#56]
该网站地址：
什么值得买app
问题重现步骤
重现该行为的步骤：
打开app弹出

页面截图
如果适用，请添加屏幕截图以帮助解释您的问题。

![IMG_1925](https://github.com/limbopro/Adblock4limbo/assets/52908005/4964cac0-d39e-4cd2-8108-2c85603aff8d)
操作系统及浏览器（请填写以下信息）:

OS: ios
Network tool ：QuantmultX
额外的背景信息

**Comment by limbopro** [comment]
@kerryeva 自行查看 readme ***
