### ISSUE TITLE
在edge浏览器中的搜索栏（默认搜索引擎为bing）进行搜索，无法正常打开网站

### ISSUE THREAD

**Issue by z1mpleee** [limbopro/Adblock4limbo#57]
**简要描述该问题**
在edge浏览器中的搜索栏（默认搜索引擎为bing）进行搜索，无法正常打开网站

**问题重现步骤**
使用edge浏览器的搜索栏进行搜索（默认搜索引擎为bing）

**页面截图**
![image](https://github.com/limbopro/Adblock4limbo/assets/45474697/bea56160-eac0-42a3-87b2-7bbdd3f5f46c)
![image](https://github.com/limbopro/Adblock4limbo/assets/45474697/71e6553f-6dc9-44c5-88e4-2b5340f4f887)
![image](https://github.com/limbopro/Adblock4limbo/assets/45474697/36bdc82e-e632-4e9a-adab-92c8678b9628)

**操作系统及浏览器（请填写以下信息）:
 - 系统: ios
 - 浏览器 edge
 - 代理工具 QuantmultX
 - 引用的重写/或模块链接 https://limbopro.com/Adblock4limbo.conf

**Comment by limbopro** [comment]
刚刚在 edge bing 搜索多次，可正常使用，未复现你所说的问题。可尝试提供更多细节；

**Comment by z1mpleee** [comment]
> 刚刚在 edge bing 搜索多次，可正常使用，未复现你所说的问题。可尝试提供更多细节；

quanx选择直连模式是可以正常使用，全局模式下disable去广告的重写规则也可以正常使用。
全局模式下disable去广告的分流规则不可以正常使用。

**Comment by limbopro** [comment]
@z1mpleee 看不懂一点。

**Comment by z1mpleee** [comment]
> 刚刚在 edge bing 搜索多次，可正常使用，未复现你所说的问题。可尝试提供更多细节；

请问是在bing网页搜索吗，还是在浏览器的地址栏搜索

**Comment by limbopro** [comment]
@z1mpleee 在edge浏览器中的搜索栏（默认搜索引擎为bing）进行搜索，可正常打开。

**Comment by z1mpleee** [comment]
> @z1mpleee 在edge浏览器中的搜索栏（默认搜索引擎为bing）进行搜索，可正常打开。

emm这么奇怪吗

**Comment by z1mpleee** [comment]
> @z1mpleee 在edge浏览器中的搜索栏（默认搜索引擎为bing）进行搜索，可正常打开。

请问你的edge浏览器是什么版本呢
