### ISSUE TITLE
泥视频更换了网址，片头出现了广告

### ISSUE THREAD

**Issue by weberyap** [limbopro/Adblock4limbo#58]
**简要描述该问题**
泥视频更换了网址，片头出现了广告，原来可以工作的网址是nivod8.tv，现在不工作的网址是nivod9.tv

**操作系统及浏览器（请填写以下信息）:** 如没有则填无需填写
 - 系统: [e.g. iOS/PC]
 -     ios 17.5
 - 浏览器 [e.g. chrome, safari]
 -    safari
 - 代理工具 [e.g. QuantmultX/Surge]
 -     小火箭
 - 引用的重写/或模块链接 [e.g. https://limbopro.com/Adblock4limbo.conf / https://limbopro.com/Adblock4limbo.sgmodule ]

**Comment by limbopro** [comment]
已修复 https://github.com/limbopro/Adblock4limbo/compare/a2c32a2247dd...85f6c3583780
