### ISSUE TITLE
一个特别全的小说网站去广告

### ISSUE THREAD

**Issue by tchzhou** [limbopro/Adblock4limbo#59]
该网站地址：
https://www.novel543.com/
问题重现步骤
重现该行为的步骤：
该网站一直都有视频弹窗广告，图片广告等
![IMG_4656](https://github.com/limbopro/Adblock4limbo/assets/32132630/76ccb5a0-f29a-4151-84af-a8d90752c163)
![IMG_4655](https://github.com/limbopro/Adblock4limbo/assets/32132630/829f1ef1-a131-4219-bdfb-5db3dbeee76a)

在哪个网页出现了广告 '...'
做了什么 '....'
出现了什么广告 '....'
Gif广告/视频广告/图片广告/弹窗...
预期想要得到的结果
对您期望发生的情况的清晰简洁的描述。

页面截图
如果适用，请添加屏幕截图以帮助解释您的问题。

操作系统及浏览器（请填写以下信息）:

Network tool [e.g. QuantmultX]
额外的背景信息
在此处添加有关该问题的任何其他上下文。

**Comment by limbopro** [comment]
已支持 https://github.com/limbopro/Adblock4limbo/compare/aaf7d5b98b03...99ccbd47e193
