### ISSUE TITLE
YouTube开启去广告后，触发规则后视频会从头播放

### ISSUE THREAD

**Issue by HanZhang1995** [limbopro/Adblock4limbo#6]
YouTube开启去广告后，触发规则后视频会从头播放

**Comment by maliouu** [comment]
最新版禁止mitm解密了，可以降级YouTube版本解决，最后一个支持YouTube mitm（脚本去广告的）最新版是16.41.2完

**Comment by Yevgnen** [comment]
开启了之后YouTube里的短视频看不了…
