### ISSUE TITLE
页面出现了广告

### ISSUE THREAD

**Issue by weberyap** [limbopro/Adblock4limbo#64]
**简要描述该问题**
iphone 更新了模块，名字从原来的Block YouTube Advertising变成了Youtube (Music) Enhance，然后youtube app里面的广告就回来了。ipad上的模块没有更新，依旧没有广告。
我不知道新模块修正或添加了什么，目前应该没有用到，但能不能把去广告的功能加回来。

**问题重现步骤**
重现该行为的步骤：
1. 在哪个网页 '...'
3. 做了什么 '....'
4. 出现了什么问题 '....'
5. Gif广告/视频广告/图片广告/弹窗...

**预期想要得到的结果**
对您期望发生的情况的清晰简洁的描述。

**页面截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**操作系统及浏览器（请填写以下信息）:** 如没有则填无需填写
 - 系统: [e.g. iOS/PC]
 - 浏览器 [e.g. chrome, safari]
 - 代理工具 [e.g. QuantmultX/Surge]
 - 引用的重写/或模块链接 [e.g. https://limbopro.com/Adblock4limbo.conf / https://limbopro.com/Adblock4limbo.sgmodule ]
 - 油猴脚本安装地址 [e.d. https://github.com/limbopro/Adblock4limbo/raw/main/Adguard/Adblock4limbo.user.js / https://greasyfork.org/scripts/443290-adblock4limbo/code/Adblock4limbo.user.js]

**额外的背景信息**
在此处添加有关该问题的任何其他上下文。

**Comment by limbopro** [comment]
@weberyap iPad 模块截图一下 看看链接地址是什么

**Comment by weberyap** [comment]
![2024_06_20_14_38_IMG_0001](https://github.com/limbopro/Adblock4limbo/assets/60670822/a9615feb-1f78-4cf4-84c7-6374b5e92c64)
![2024_06_20_14_38_IMG_0002](https://github.com/limbopro/Adblock4limbo/assets/60670822/a6500605-0754-4806-8107-d903dcf34f56)

**Comment by limbopro** [comment]
@weberyap 你直接复制iPad上模块内的代码到iPhone试试。

**Comment by weberyap** [comment]
复制过去是没有问题的，没有广告了，但是不能更新，一个个改也太麻烦了，虽然我已经一个个的改过了，哪天手贱又更新一下就要再来一遍了，当然这不是你的问题，这是我的问题，我只是问问能不能把旧模块和新模块合并呀？

**Comment by limbopro** [comment]
@weberyap 你可以先复制 iPad 上那个还生效的【旧模块】的代码内容到备忘录，然后再分别在 iPad/iPhone 新建模块，粘贴该代码内容；最后再禁用刚刚复制代码内容的模块。 

如果你想跟更新后的新模块合并，你可以自行对比新旧模块内容，然后复制到刚刚新建的模块内即可；

以上。
