### ISSUE TITLE
漫步者耳机app去广告申请

### ISSUE THREAD

**Issue by zzs0915** [limbopro/Adblock4limbo#65]
该网站地址：
![IMG_0549](https://github.com/limbopro/Adblock4limbo/assets/65374703/92da2e57-8755-49f5-8c91-522d114494b6)
![IMG_0550](https://github.com/limbopro/Adblock4limbo/assets/65374703/39c95d16-760b-42fb-82d6-4597b9054db5)

edifier connect软件，打开就如图的广告。通过圈叉看到的网址信息如图。

**Comment by limbopro** [comment]
@zzs0915 app 去不了一点

**Comment by zzs0915** [comment]
> @zzs0915 app 去不了一点

去不了开屏广告吗
