### ISSUE TITLE
您好 win11edge页面锁密码记错了 怎么查看、重设或者取消？

### ISSUE THREAD

**Issue by Actor-Flowers** [limbopro/Adblock4limbo#66]
**简要描述该问题**
密码错误❌！请重新输入...
**问题重现步骤**
重现该行为的步骤：
1. 在哪个网页 '...'
3. 做了什么 '....'
4. 出现了什么问题 '....'
5. Gif广告/视频广告/图片广告/弹窗...

**预期想要得到的结果**
对您期望发生的情况的清晰简洁的描述。

**页面截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**操作系统及浏览器（请填写以下信息）:** 如没有则填无需填写
 - 系统: [e.g. iOS/PC]
 - 浏览器 [e.g. chrome, safari]
 - 代理工具 [e.g. QuantmultX/Surge]
 - 引用的重写/或模块链接 [e.g. https://limbopro.com/Adblock4limbo.conf / https://limbopro.com/Adblock4limbo.sgmodule ]
 - 油猴脚本安装地址 [e.d. https://github.com/limbopro/Adblock4limbo/raw/main/Adguard/Adblock4limbo.user.js / https://greasyfork.org/scripts/443290-adblock4limbo/code/Adblock4limbo.user.js]

**额外的背景信息**
在此处添加有关该问题的任何其他上下文。

**Comment by limbopro** [comment]
@Actor-Flowers 浏览器控制台输入代码  getCookie('lock_screen_pwd')  可以获取你设置的密码；https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/console/
