### ISSUE TITLE
小火箭module中整合rule配置

### ISSUE THREAD

**Issue by PaTTeeL** [limbopro/Adblock4limbo#75]
**简要描述该问题**
小火箭的模块是支持 `[Rule]` 配置段的，可否把 `[Adblock4limbo.list](https://github.com/limbopro/Adblock4limbo/blob/main/rule/Shadowrocket/Adblock4limbo.list)` 整合到https://github.com/limbopro/Adblock4limbo/blob/main/Adblock4limbo.module 模块里，这样就可以简化安装操作，不需要再修改主配置文件加入Adblock4limbo.list的部分，实现一次安装立刻生效。

**预期想要得到的结果**
小火箭只需安装Adblock4limbo.module，不需要在配置文件中再添加远程规则Adblock4limbo.list即可以实现Adblock4limbo的全部功能。

**Comment by limbopro** [comment]
@PaTTeeL 自己动手添加下分流 list 就好了

**Comment by PaTTeeL** [comment]
> @PaTTeeL 自己动手添加下分流 list 就好了

我这里算是两难，用快捷指令更新配置时添加分流list，p12证书会失效，每次都要重新生成和安装。
目前的选择是固定配置文件，将黑名单和白名单模块导入配置，这样每次只要更新模块就可以搞定黑白名单了，但据我所知模块的优先权是高于配置，所以如果模块中没有分流规则，配置中的分流规则可能是匹配不到的。
