### ISSUE TITLE
去广告

### ISSUE THREAD

**Issue by ITea312** [limbopro/Adblock4limbo#79]
该网站地址：https://ww7.pornhoarder.tv

问题重现步骤
重现该行为的步骤：

在哪个网页出现了广告 'https://ww7.pornhoarder.tv/video/eva-lovia-onlyfans/cFFycVQxOTRYMVVOYnVOOGNZTDlQanRxMGdrSUM4cFlqN2U4YnRIejc5RT0='
做了什么 '点击广告上方的关闭按钮进行弹窗重新加载网页；点击播放按钮进行弹窗'
出现了什么广告'Gif广告/图片广告/弹窗'
预期想要得到的结果'实现去广告、弹窗，并通过该视频去除该网址其他视频同样类似情况的广告、弹窗'
对您期望发生的情况的清晰简洁的描述。

页面截图
如果适用，请添加屏幕截图以帮助解释您的问题。

操作系统及浏览器（请填写以下信息）:

OS: [iOS16.6.1]
Browser [chrome]
Version [127.0.6533.56]
Network tool [QuantmultX]
额外的背景信息
在此处添加有关该问题的任何其他上下文。

**Comment by limbopro** [comment]
已更新支持 ww7.pornhoarder.tv 去广告，更新分流规则后食用；正确配置去广告分流规则及重写参阅 -> https://limbopro.com/archives/12904.html
