### ISSUE TITLE
重写规则导致"通义"无法使用

### ISSUE THREAD

**Issue by cweijan** [limbopro/Adblock4limbo#82]
Adblock4limbo.conf启用后, 会导致移动端的AI产品"通义"显示网络错误从而无法使用, 经过排查, 由第63行的规则导致

<img width="1459" alt="image" src="https://github.com/user-attachments/assets/c8c301f5-2fea-4e72-adc3-8dac939b61c3">

**Comment by limbopro** [comment]
@cweijan 自行排除相关主机名即可。

**Comment by cweijan** [comment]
我知道, 我只是给你提醒下这个规则有负作用.

**Comment by limbopro** [comment]
@cweijan 🫡
