### ISSUE TITLE
今日水印相机开屏广告

### ISSUE THREAD

**Issue by 203081000** [limbopro/Adblock4limbo#85]
代理软件为圈X
![IMG_2989](https://github.com/user-attachments/assets/cd437819-c748-4201-9b48-45beb2cede1e)
![IMG_2988](https://github.com/user-attachments/assets/f4004c4d-e1aa-421c-b326-e70c1fade6f5)
并发Http请求太多了，我识别不出来哪个是广告的地址。

**Comment by limbopro** [comment]
@203081000
