### ISSUE TITLE
Loon開啟missav.com無法連線

### ISSUE THREAD

**Issue by leo810512** [limbopro/Adblock4limbo#89]
**简要描述该问题**

**问题重现步骤**
重现该行为的步骤：
1. 在哪个网页 'missav.com'
3. 做了什么 '瀏覽missav網頁'
4. 出现了什么问题 '網頁完全無法連線'

**预期想要得到的结果**
对您期望发生的情况的清晰简洁的描述。

**页面截图**
![IMG_0538](https://github.com/user-attachments/assets/a89d4828-1dcc-49cc-a71b-870b542f543d)

**操作系统及浏览器（请填写以下信息）:** 如没有则填无需填写
 - 系统: [ iOS]
 - 浏览器 [safari]
 - 代理工具 [Loon]
 - 引用的重写/或模块链接 [兩種都不行 https://limbopro.com/Adblock4limbo.conf / https://limbopro.com/Adblock4limbo.sgmodule ]
都有使用Script-Hub

**额外的背景信息**
![IMG_0539](https://github.com/user-attachments/assets/2e2ca039-08f5-4b96-bc80-1b405602df64)
![IMG_0540](https://github.com/user-attachments/assets/633516e3-e9f4-4e1f-9f17-63cba12b18fa)
![IMG_0541](https://github.com/user-attachments/assets/5b4ff84b-0a13-48d1-a4e1-401484994f3e)

**Comment by limbopro** [comment]
@leo810512 你给 missav 添加一条分流，让他走代理。

**Comment by limbopro** [comment]
Loon -> 设置 -> MitM -> 域名 ，关闭 MitM over http/2 选项。
