### ISSUE TITLE
DDRK这种良心网站都tm去广告

### ISSUE THREAD

**Issue by Anehta** [limbopro/Adblock4limbo#9]
你妈死了

**Comment by Anehta** [comment]
整这傻逼项目是因为站长杀了你全家吗

**Comment by limbopro** [comment]
如果此项目伤害了**你对低端影视的感情**，在此博主对您表示非常抱歉；本项目仅出于个人兴趣进行维护，如有冒犯，敬请谅解；如需屏蔽 Chrome/Safari（For Mac / Windows）上的网页广告，博主推荐您是用 Adguard 或 ublock origin 提供的免费浏览器扩展；参阅 ：https://limbopro.com/archives/12904.html

**Comment by Karmylr** [comment]
笑死我了
