### ISSUE TITLE
误杀了百度知道的页面

### ISSUE THREAD

**Issue by pyb2000** [limbopro/Adblock4limbo#91]
**简要描述该问题**

**问题重现步骤**
重现该行为的步骤：
1. [在哪个网页 '...'](https://zhidao.baidu.com/question/132901499.html)
2. 正文被杀掉了
3. 关闭此脚本后正常

**预期想要得到的结果**
对您期望发生的情况的清晰简洁的描述。

**页面截图**
如果适用，请添加屏幕截图以帮助解释您的问题。
![image](https://github.com/user-attachments/assets/2ae2d4ae-fb1f-4f72-9d04-d3ebd78acb96)
![image](https://github.com/user-attachments/assets/52fc37dc-96e7-43c6-9bca-44a5cbcac518)

**操作系统及浏览器（请填写以下信息）:** 如没有则填无需填写
 - 系统: [win10]
 - 浏览器 [Cent Browser
版本 5.1.1130.129（正式版本） （64 位） (Chromium 118.0.5993.159)i]
 - 代理工具 [Proxy SwitchyOmega
2.5.21]

![image](https://github.com/user-attachments/assets/7493a1b7-74c6-42de-9dbf-2d6e9100baa5)

**额外的背景信息**
在此处添加有关该问题的任何其他上下文。

**Comment by limbopro** [comment]
已修复 https://github.com/limbopro/Adblock4limbo/compare/9b8a5e3c9b45...7b5ddf365724 ；更新脚本：https://github.com/limbopro/Adblock4limbo/raw/main/Adguard/Adblock4limbo.user.js
