### ISSUE TITLE
某些页面不匹配

### ISSUE THREAD

**Issue by dragonadd** [limbopro/Adblock4limbo#94]
**简要描述该问题**
在一些需要用到QQ号登录的网站，跳转QQ网页登录，
在安全验证、选择最符合的图片时候，
脚本的滚动条会单独出现在安全验证里面、而不是像其他页面在页面的最右边，
从而挡住了安全验证的“确定”按钮，无法点击。当关闭脚本后可以点击。

**问题重现步骤**
重现该行为的步骤：
1. 在哪个网页 'QQ安全验证页面，比如登录虎牙、斗鱼等可以用qq登录的平台，然后跳转qq登录页面-使用密码登录'
3. 做了什么 '脚本处于开启'
4. 出现了什么问题 '无法点击确定按钮'
5. 停止脚本运行可以正常点击

**预期想要得到的结果**
导航按钮滚动条能移出安全验证页面

**页面截图**
如果适用，请添加屏幕截图以帮助解释您的问题。
![image](https://github.com/user-attachments/assets/77ac834d-1059-4fd2-a9c6-4431f914cd57)
![image](https://github.com/user-attachments/assets/daebf889-338d-4c1a-afe8-eabc98bfb753)
![image](https://github.com/user-attachments/assets/31b5ad5b-3e40-48e4-97e7-04efc4c86a99)

**操作系统及浏览器（请填写以下信息）:** 如没有则填无需填写
 - 系统: [PC] 
 - 浏览器 [chrome]
 - 油猴脚本安装地址 [ https://github.com/limbopro/Adblock4limbo/raw/main/Adguard/Adblock4limbo.user.js]

**Comment by limbopro** [comment]
@dragonadd Fixed. Try it again.

**Comment by limbopro** [comment]
@dragonadd 导航按钮默认追加到原网页的head 标签后 body 标签前的，基于网页本身位置进行定位。截图所示网页 body 的宽和高大概就只有那么一小块。

**Comment by dragonadd** [comment]
> @dragonadd Fixed. Try it again.

Done. Thanks.
