### ISSUE TITLE
漫画网站去广告

### ISSUE THREAD

**Issue by Wushuangjiang424** [limbopro/Adblock4limbo#98]
该网站地址：www.colamanga.com

问题重现步骤     不但阅读的时候会有广告，且点击下一章的时候会出现新的空白页
重现该行为的步骤：
![cdec19c1a8a583777769c1016fe705c](https://github.com/user-attachments/assets/b8ba27f9-d364-4fb1-bada-c16cfc1a8539)

在哪个网页出现了广告 '...'
做了什么 '....'
出现了什么广告 '....'
Gif广告/视频广告/图片广告/弹窗...
预期想要得到的结果
对您期望发生的情况的清晰简洁的描述。

页面截图
如果适用，请添加屏幕截图以帮助解释您的问题。

操作系统及浏览器（请填写以下信息）:

OS: [e.g. iOS]   IOS 17
Browser [e.g. chrome, safari]  chrome
Network tool [e.g. QuantmultX]   surge
额外的背景信息
在此处添加有关该问题的任何其他上下文。

**Comment by limbopro** [comment]
@Wushuangjiang424 暂没看到广告；可按文章配置重写与分流规则 -> https://limbopro.com/archives/12904.html

**Comment by Wushuangjiang424** [comment]
你好，博主，你给我的链接无法打开，是因为什么吗？我是否可以针对该网站单独写一条规则？

毒奶博主 ***@***.***>于2024年12月25日 周三22:48写道：

**Comment by limbopro** [comment]
@Wushuangjiang424 挂代理访问。

**Comment by Wushuangjiang424** [comment]
毒奶模块添加到surge，出现以下问题：
1.其他网站有误杀情况，能不能教教我如何把误杀网站的规则在模块中提出？
2.大佬！cola漫画用chrome看还是有广子呀!我的surge开了模块，开了MITM,也开了HTTP重写，是不是需要google重定向？还是我的配置中规则有缺漏？希望大佬可以传授点经验😭

毒奶博主 ***@***.***> 于2024年12月26日周四 20:32写道：

**Comment by limbopro** [comment]
@Wushuangjiang424 1.目前去网页广告计划支持列表 https://github.com/limbopro/Adblock4limbo/blob/main/Adblock4limbo.weblist 

2.这边没看到广告
